name: StaffPlusPlusDiscord
main: be.garagepoort.staffplusplus.discord.StaffPlusPlusDiscord
version: 1.16.12
api-version: 1.13
depend: [StaffPlus]
commands:
    staffplusplusdiscord:
        description: reload the plugin
        usage: /<command> [reload]
        aliases: [staffplusplusdiscord]